apiVersion: litmuschaos.io/v1alpha1
kind: ChaosSchedule
metadata:
  name: sc-pod-net-latency
spec:
  schedule:
    repeat:
      properties:
        #format should be like "10m" or "2h" accordingly for minutes or hours
        minChaosInterval: "10m"
  engineTemplateSpec:
    engineState: 'active'
    appinfo:
      appns: 'hipster-shop'
      applabel: 'product=hipster-shop'
      appkind: 'deployment'
    annotationCheck: 'false'
    chaosServiceAccount: pod-delete-sa
    jobCleanUpPolicy: 'delete'
    components:
      runner:
        runnerAnnotations:
          sidecar.istio.io/inject: "false"
    experiments:
      - name: pod-network-latency
        spec:
          components:
            experimentAnnotations:
              sidecar.istio.io/inject: "false"
            env:
              - name: TOTAL_CHAOS_DURATION
                value: '120' # in seconds

              - name: NETWORK_LATENCY
                value: '2000'

              # provide the name of container runtime
              # for litmus LIB, it supports docker, containerd, crio
              # for pumba LIB, it supports docker only
              - name: CONTAINER_RUNTIME
                value: 'docker'

              # provide the socket file path
              - name: SOCKET_PATH
                value: '/var/run/docker.sock'

              ## percentage of total pods to target
              - name: PODS_AFFECTED_PERC
                value: '45'

              #Network interface inside target container
              - name: NETWORK_INTERFACE
                value: 'eth0'
