apiVersion: litmuschaos.io/v1alpha1
kind: ChaosSchedule
metadata:
  name: sc-node-memory-hog
spec:
  schedule:
    repeat:
      properties:
        #format should be like "10m" or "2h" accordingly for minutes or hours
        minChaosInterval: "15m"
  engineTemplateSpec:
    engineState: 'active'
    appinfo:
      appns: 'hipster-shop'
      applabel: 'product=hipster-shop'
      appkind: 'deployment'
    annotationCheck: 'false'
    chaosServiceAccount: pod-delete-sa
    jobCleanUpPolicy: 'delete'
    components:
      runner:
        runnerAnnotations:
          sidecar.istio.io/inject: "false"
    experiments:
      - name: node-memory-hog
        spec:
          components:
            experimentAnnotations:
              sidecar.istio.io/inject: "false"
            env:
              # set chaos duration (in sec) as desired
              - name: TOTAL_CHAOS_DURATION
                value: '700'

              ## Specify the size as percent of total node capacity Ex: '30'
              ## Note: For consuming memory in mebibytes change the variable to MEMORY_CONSUMPTION_MEBIBYTES
              - name: MEMORY_CONSUMPTION_PERCENTAGE
                value: '70'

              ## percentage of total nodes to target
              - name: NODES_AFFECTED_PERC
                value: '60'

              # provide the comma separated target node names
              - name: TARGET_NODES
                value: 'gke-onlineboutique-default-pool-112e98a2-foka,gke-onlineboutique-default-pool-112e98a2-osgl'
