apiVersion: litmuschaos.io/v1alpha1
kind: ChaosSchedule
metadata:
  name: sc-node-drain2
spec:
  schedule:
    repeat:
      properties:
        #format should be like "10m" or "2h" accordingly for minutes or hours
        minChaosInterval: "20m"
  engineTemplateSpec:
    engineState: 'active'
    appinfo:
      appns: 'hipster-shop'
      applabel: 'product=hipster-shop'
      appkind: 'deployment'
    annotationCheck: 'false'
    chaosServiceAccount: pod-delete-sa
    jobCleanUpPolicy: 'delete'
    components:
      runner:
        runnerAnnotations:
          sidecar.istio.io/inject: "false"
    experiments:
      - name: node-drain
        spec:
          components:
            experimentAnnotations:
              sidecar.istio.io/inject: "false"
            # nodeSelector:
            #   # provide the node labels
            #   kubernetes.io/hostname: 'node02'
            env:
              - name: TOTAL_CHAOS_DURATION
                value: '1200'

              # enter the target node name
              - name: TARGET_NODE
                value: 'gke-onlineboutique-default-pool-112e98a2-ghbb'
