apiVersion: litmuschaos.io/v1alpha1
kind: ChaosSchedule
metadata:
  name: sc-node-iostress
spec:
  schedule:
    repeat:
      properties:
        #format should be like "10m" or "2h" accordingly for minutes or hours
        minChaosInterval: "15m"
  engineTemplateSpec:
    engineState: 'active'
    appinfo:
      appns: 'hipster-shop'
      applabel: 'product=hipster-shop'
      appkind: 'deployment'
    annotationCheck: 'false'
    chaosServiceAccount: pod-delete-sa
    jobCleanUpPolicy: 'delete'
    components:
      runner:
        runnerAnnotations:
          sidecar.istio.io/inject: "false"
    experiments:
      - name: node-io-stress
        spec:
          components:
            experimentAnnotations:
              sidecar.istio.io/inject: "false"
            env:
              # set chaos duration (in sec) as desired
              - name: TOTAL_CHAOS_DURATION
                value: '700'

              ## specify the size as percentage of free space on the file system
              - name: FILESYSTEM_UTILIZATION_PERCENTAGE
                value: '10'

              ## Number of core of CPU
              - name: CPU
                value: '3'

              ## Total number of workers default value is 4
              - name: NUMBER_OF_WORKERS
                value: '4'

              ## percentage of total nodes to target
              - name: NODES_AFFECTED_PERC
                value: '50'

              # provide the comma separated target node names
              - name: TARGET_NODES
                value: 'gke-onlineboutique-default-pool-112e98a2-foka, gke-onlineboutique-default-pool-112e98a2-osgl'
